/* FILE_INFO_START
 * Copyright (C) 2016 
 * 
 * ***********************************************************************
 * This file is part of SpadSimulator
 * 
 * SpadSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SpadSimulator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SpadSimulator.  If not, see <http://www.gnu.org/licenses/>.
 * ***********************************************************************
 * 
 * File        : afterpulse.hh
 * Author      : Audrey Corbeil Therrien <audrey.corbeil.therrien@usherbrooke.ca>
 * Author      : Valentin Libioulle <valentin.libioulle@usherbrooke.ca>
 * Created     : Thu Mar 10 08:39:50 2016 -0500 by valentin
 * 
 * FILE_INFO_END */


#ifndef AFTERPULSE_PARTICLES_H
#define AFTERPULSE_PARTICLES_H

#include "particle.hh"

/**
 * @brief An afterpulse is generated by another particle creating an avalanche.
 */
class Afterpulse : public Particle {
private:
    Afterpulse();
    Afterpulse(const Afterpulse&);
    Afterpulse& operator=(const Afterpulse&);
    
protected:
    Particle* parent; //!< The parent particle
    
public:
    /**
     * @brief Create an afterpulse from the parent particle and information to hit a sensor.
     * 
     * @param parent The parent particle.
     * @param globalTime The time when to hit the sensor.
     * @param position The position where to hit the sensor.
     */
    Afterpulse(Particle* parent, const double& globalTime, const Position3D& position);
    
    /**
     * @brief Destructor
     */
    virtual ~Afterpulse() {}
};

#endif //AFTERPULSE_PARTICLES_H