include(${CMAKE_CURRENT_SOURCE_DIR}/sensor/matrix/CMakeLists.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/sensor/pde/CMakeLists.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/sensor/quench/CMakeLists.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/sensor/sensor/CMakeLists.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/sensor/state/CMakeLists.cmake)
