MACRO(FILES_INCLUDE_FOLDER)
  INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/${FILES_FOLDER}/include")

  FOREACH (_header ${FILES_HEADERS})
    FILE (COPY "${CMAKE_CURRENT_SOURCE_DIR}/${FILES_FOLDER}/include/${_header}" DESTINATION "${PROJECT_BINARY_DIR}/include/Files")
    SET(FILES_INSTALL_HEADERS "${FILES_INSTALL_HEADERS}"
                              "${FILES_FOLDER}/include/${_header}")
  ENDFOREACH ()
  
  
  FOREACH(_source ${FILES_SOURCES})
    SET (SRC_FILES ${SRC_FILES} "${CMAKE_CURRENT_SOURCE_DIR}/${FILES_FOLDER}/src/${_source}")
  ENDFOREACH()

ENDMACRO()
